ballerina-platform/module-ballerina-url

build.gradle, encoding-ballerina/Ballerina.toml, encoding-ballerina/build.gradle, encoding-ballerina/src/encoding/encoding.bal, encoding-ballerina/src/encoding/encoding_errors.bal, encoding-ballerina/src/encoding/tests/unit-tests/uri-component-test.bal, encoding-native/build.gradle, encoding-native/src/main/java/org/ballerinalang/stdlib/encoding/Constants.java, encoding-native/src/main/java/org/ballerinalang/stdlib/encoding/EncodingUtil.java, encoding-native/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/Decode.java, encoding-native/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/Encode.java, gradle.properties
- $subject
- Fixes https://github.com/ballerina-platform/module-ballerina-encoding/issues/3
- Fixes https://github.com/ballerina-platform/module-ballerina-encoding/issues/4
- Sync with recent error changes
- Add the release plugin
- Add packaging configs
=> Sync module with recent error changes

encoding-ballerina/build.gradle
$subject
- Pack `encoding-native` lib
=> Enable native lib pack

encoding-ballerina/build.gradle
=> Clean native jar configs

.gitignore, build.gradle
=> Add unversioned files to gitignore

encoding-native/src/main/java/org/ballerinalang/stdlib/encoding/Constants.java, gradle.properties
=> Upgrade module and ballerina versions

build.gradle
=> Update Nexus URL

encoding-native/src/main/java/org/ballerinalang/stdlib/encoding/Constants.java, gradle.properties
=> Upgrade version

build.gradle, encoding-ballerina/Ballerina.toml, encoding-ballerina/build.gradle, gradle.properties
=> Add stdlib dependency configs

encoding-ballerina/src/encoding/tests/unit-tests/bas64-url-encoding-test.bal, encoding-ballerina/src/encoding/tests/unit-tests/uri-component-test.bal
=> Refactor unit tests

.github/workflows/build-master.yml, README.md, encoding-ballerina/build.gradle
This PR updates the readme of the repository with the required configurations to run `./gradlew test` command.
=> Update readme and configurations

encoding-ballerina/src/encoding/encoding.bal
=> Fix encoding module for object change

encoding-native/src/main/java/org/ballerinalang/stdlib/encoding/EncodingUtil.java, encoding-native/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/Decode.java, encoding-native/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/Encode.java
=> Migrate jBallerina Runtime APIs

.github/workflows/pull-request.yml, encoding-ballerina/src/encoding/encoding.bal
=> Update encoding module with isolated functions

.github/workflows/publish-release.yml, .github/workflows/pull-request.yml, build.gradle, encoding-ballerina/build.gradle
=> Update GitHub release workflow

encoding-native/src/main/java/org/ballerinalang/stdlib/encoding/Constants.java, encoding-native/src/main/java/org/ballerinalang/stdlib/encoding/EncodingUtil.java
=> Refactor code

build.gradle, encoding-native/build.gradle, gradle.properties
=> Enable checkstyle and spotbugs

encoding-ballerina/src/encoding/tests/unit-tests/base64_url_encoding_decoding_test.bal, encoding-ballerina/src/encoding/tests/unit-tests/uri_component_encoding_decoding_test.bal
=> Refactor test cases

encoding-native/src/main/java/module-info.java, encoding-native/src/main/java/org/ballerinalang/stdlib/encoding/Constants.java, encoding-native/src/main/java/org/ballerinalang/stdlib/encoding/EncodingUtil.java, encoding-native/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/Decode.java, encoding-native/src/main/java/org/ballerinalang/stdlib/encoding/nativeimpl/Encode.java
Refactor ballerina runtime api usages
=> Migrate ballerina runtime apis

build.gradle, encoding-ballerina/Ballerina.toml, encoding-ballerina/build.gradle, encoding-ballerina/src/encoding/tests/unit-tests/uri_component_encoding_decoding_test.bal, gradle.properties
This PR replaces usages of `ballerina/stringutils` module with the `string` lang lib functions.
=> Replace usages of ballerina/stringutils module

build.gradle
$subject since it is missed with https://github.com/ballerina-platform/module-ballerina-encoding/pull/38
=> Remove unused ballerina/io dependency

encoding-ballerina/src/encoding/tests/unit-tests/base64_url_encoding_decoding_test.bal, encoding-ballerina/src/encoding/tests/unit-tests/uri_component_encoding_decoding_test.bal
=> Mark the unit test functions as isolated

build.gradle, encoding-ballerina/build.gradle
=> Refactor gradle configurations

encoding-ballerina/tests/uri_component_encoding_decoding_test.bal
=> Refactor strings API usages

encoding-ballerina/build.gradle
> Update ballerina command to bal command
=> Update ballerina command to bal command

encoding-ballerina/encoding.bal, encoding-ballerina/init.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Change the name of the `java` langlib module to `jballerina.java`

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, encoding-ballerina/build.gradle
=> Publish code coverage exec file as a maven artifact

.github/workflows/build-master.yml, .github/workflows/pull-request.yml
$subject
Related to https://github.com/ballerina-platform/module-ballerina-encoding/pull/65
=> Fix github actions

encoding-ballerina/build.gradle
=> Refactor build task order

encoding-ballerina/build.gradle
=> Avoid running tests twice when publishing

build.gradle, encoding-ballerina/build.gradle
=> Publish testable jar for code coverage

encoding-ballerina/build.gradle
> Renames the extension of the package distribution file from balo to bala 
> Fixes ballerina-platform/ballerina-lang#28476
=> Change ballerina archive extension to bala

README.md, encoding-ballerina/Package.md
=> Update docs for swan-lake URL change

encoding-ballerina/build.gradle
=> Parrameterize the hard coded module names

.github/workflows/publish-release.yml, encoding-ballerina/build.gradle, gradle.properties
- Subtask of https://github.com/ballerina-platform/ballerina-standard-library/issues/957
- Bump the next version to a minor alpha version
- Improve the build scripts and actions to publish the artifacts to the Ballerina central during a release
=> Enable publishing to Ballerina Central during release

gradle.properties
=> Update ballerina lang version to next snapshot

build.gradle, encoding-ballerina/build.gradle
=> Re-order build tasks to enable publishing to central

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, encoding-ballerina/build.gradle
=> Remove publishing exec artifacts and archiving test json

url-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
=> Add extracted bala in the zip artifact

url-ballerina/url_errors.bal, url-native/src/main/java/org/ballerinalang/stdlib/url/Constants.java
=> Update error type

url-ballerina/build.gradle
> Add -c flag to build command
> Related to https://github.com/ballerina-platform/ballerina-lang/pull/29032
=> Add -c flag to build command

build.gradle, url-ballerina/build.gradle
=> Strip stdlib dependency version

url-ballerina/build.gradle
=> Fix publishing workflow

url-ballerina/build.gradle
Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381
=> Set flag to enable Jacoco Coverage XML generation

build-config/checkstyle/build.gradle, build.gradle, gradle.properties, url-ballerina/build.gradle
Standardize build script of Ballerina module
=> Apply Gradle Ballerina plugin for Ballerina module build script

README.md, url-ballerina/Module.md, url-ballerina/Package.md, url-ballerina/tests/url_test.bal, url-ballerina/url.bal, url-ballerina/url_errors.bal
$subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/584
=> Improve the API documentation and markdown files

url-ballerina/build.gradle
=> Remove redundant config

url-ballerina/build.gradle
Remove overriding testCoverageParam and use the value from the gradle plugin.
=> Remove overriding testCoverageParam

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml
This is related to https://github.com/ballerina-platform/ballerina-release/issues/547
=> Improve GitHub action workflow scripts

url-ballerina/Package.md
This is a part of https://github.com/ballerina-platform/ballerina-standard-library/issues/1462
=> Update Package.md links into HTML format

README.md, url-ballerina/Module.md, url-ballerina/Package.md
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1563
=> Improve documentation

gradle.properties
Related to https://github.com/ballerina-platform/module-ballerina-url/pull/219
=> Update group id

ballerina/Ballerina.toml
Related to https://github.com/ballerina-platform/module-ballerina-url/pull/219
=> Remove redundant configs

.github/workflows/publish-release.yml, .github/workflows/trivy-scan.yml
This PR integrates the [Trivy](https://github.com/aquasecurity/trivy) vulnerability scanner for repository file system and it will check and generate the report daily or on demand and before the release.
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/1849
=> Integrate Trivy vulnerability scanner

ballerina/tests/url_test.bal
$subject fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2445
=> Refactor code base

.github/workflows/publish-release.yml
=> Fix steps order in publish action

ballerina/tests/url_test.bal
=> Remove unused variable

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/tests/url_test.bal
=> Update dependencies to the latest timestamp version

ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml
> $Subject
> Related to [`Add details for native jars used in the standard library #3117`](https://github.com/ballerina-platform/ballerina-standard-library/issues/3117)
N/A
=> Add details for native jars used in the standard library

ballerina/Dependencies.toml
=> [Automated] Update the `Dependencies.toml`

.github/workflows/build-timestamped-master.yml, .github/workflows/build-with-bal-test-graalvm.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/checkstyle/build.gradle, build-config/resources/Ballerina.toml, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, native/build.gradle
=> [java_17_migration] Migrate build to Java-17

README.md, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Fix Oracle jdk download link and gradle version

.gitattributes, gradle.properties
=> Add git attribute and bump lang version

.github/workflows/build-with-bal-test-graalvm.yml
> $Subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/4787
N/A
=> [2201.7.x] Add GraalVM Check for `2201.7.x` branch

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml
> $Subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/4778
N/A
=> Migrate to centralised reusable workflows

build.gradle, gradle.properties
> $Subject
Related to: https://github.com/ballerina-platform/ballerina-library/issues/6106
N/A
=> Update ballerina gradle plugin verison

.github/workflows/build-timestamped-master.yml, .github/workflows/build-with-bal-test-graalvm.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, README.md, ballerina/Ballerina.toml, build-config/resources/Ballerina.toml, build.gradle, gradle.properties, native/build.gradle
=> Migrate to Java 21

ballerina/Ballerina.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Prepare for Update11 release
